
services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    networks:
      - app_network  # ✅ Add this network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
      - mongo

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    networks:
      - app_network  # ✅ Add this network
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    networks:
      - app_network  # ✅ Add this network
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    container_name: mongo_db
    networks:
      - app_network  # ✅ Add this network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: docdatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    container_name: react_frontend
    networks:
      - app_network
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      networks:
        - app_network  # ✅ Ensure it's in the same network as PostgreSQL
      ports:
        - "5050:80"  # ✅ You can access pgAdmin at http://localhost:5050
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com  # ✅ Change this as needed
        PGADMIN_DEFAULT_PASSWORD: admin  # ✅ Change this as needed
      depends_on:
        - postgres


networks:
  app_network:  # ✅ Define the network
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  mongo_data:
